cameras:
  pi_0:
    autofocus_enabled: false
    friendly_name: PiCamera 0 (imx477)
    has_autofocus: false
    iso: 1600
    max_height: 2592
    max_width: 4608
    path: 0
    resolution: 4056x3040
    resolutions:
    - 1332x990
    - 2028x1080
    - 2028x1520
    - 4056x3040
    shutter_speed: 1/30s
    shutter_speed_range:
    - 30
    - 1000
    type: pi
defaults:
  prefix: mqtt2
overlay_settings: true
performance_mode: auto
