cameras:
  pi_0:
    autofocus_enabled: false
    friendly_name: PiCamera 0 (imx477)
    has_autofocus: false
    iso: 400
    max_height: 2592
    max_width: 4608
    path: 0
    resolution: 2028x1520
    resolutions:
    - 1332x990
    - 2028x1080
    - 2028x1520
    - 4056x3040
    shutter_speed: 1/125s
    shutter_speed_range:
    - 30
    - 1000
    type: pi
  pi_1:
    autofocus_enabled: true
    friendly_name: PiCamera 1 (imx708)
    has_autofocus: true
    iso: 1600
    max_height: 2592
    max_width: 4608
    path: 1
    resolution: 2304x1296
    resolutions:
    - 1536x864
    - 2304x1296
    - 4608x2592
    shutter_speed: 1/250s
    shutter_speed_range:
    - 30
    - 1000
    type: pi
defaults:
  prefix: IMG
performance_mode: high
