cameras:
  pi_0:
    friendly_name: PiCamera 0 (imx708)
    has_autofocus: true
    path: 0
    resolutions:
    - 640x480
    - 800x600
    - 1280x720
    - 1920x1080
    - 2304x1296
    - 4608x2592
    shutter_speed_range:
    - 30
    - 1000
    type: pi
  pi_1:
    friendly_name: PiCamera 1 (imx477)
    has_autofocus: false
    path: 1
    resolutions:
    - 640x480
    - 800x600
    - 1280x720
    - 1920x1080
    - 2304x1296
    - 4608x2592
    shutter_speed_range:
    - 30
    - 1000
    type: pi
  pi_2:
    friendly_name: 'PiCamera 2 (FHD Camera: FHD Camera)'
    has_autofocus: false
    path: 2
    resolutions:
    - 640x480
    - 800x600
    - 1280x720
    - 1920x1080
    shutter_speed_range: unavailable
    type: pi
