cameras:
  pi_0:
    autofocus_enabled: true
    friendly_name: PiCamera 0 (imx477)
    has_autofocus: true
    path: 0
    resolution: 1280x720
    resolutions:
    - 640x480
    - 800x600
    - 1280x720
    - 1920x1080
    - 2304x1296
    - 4608x2592
    shutter_speed: Auto
    shutter_speed_range:
    - 30
    - 1000
    type: pi
  pi_1:
    autofocus_enabled: false
    friendly_name: PiCamera 1 (imx708)
    has_autofocus: true
    path: 1
    resolution: 2304x1296
    resolutions:
    - 640x480
    - 800x600
    - 1280x720
    - 1920x1080
    - 2304x1296
    - 4608x2592
    shutter_speed: 1/125s
    shutter_speed_range:
    - 30
    - 1000
    type: pi
defaults:
  prefix: mqtt_test
